-- AlterTable
ALTER TABLE "Cupons" ALTER COLUMN "Codigo" SET NOT NULL,
ALTER COLUMN "Codigo" SET DATA TYPE TEXT,
ALTER COLUMN "Regras" SET NOT NULL,
ALTER COLUMN "Regras" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Produto" ALTER COLUMN "Nome" SET NOT NULL,
ALTER COLUMN "Nome" SET DATA TYPE TEXT,
ALTER COLUMN "Categoria" SET NOT NULL,
ALTER COLUMN "Categoria" SET DATA TYPE TEXT,
ALTER COLUMN "Caracteristicas" SET NOT NULL,
ALTER COLUMN "Caracteristicas" SET DATA TYPE TEXT,
ALTER COLUMN "Foto" SET NOT NULL,
ALTER COLUMN "Foto" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "Nome" SET NOT NULL,
ALTER COLUMN "Nome" SET DATA TYPE TEXT,
ALTER COLUMN "Email" SET NOT NULL,
ALTER COLUMN "Email" SET DATA TYPE TEXT,
ALTER COLUMN "Hash" SET NOT NULL,
ALTER COLUMN "Hash" SET DATA TYPE TEXT,
ALTER COLUMN "Salt" SET NOT NULL,
ALTER COLUMN "Salt" SET DATA TYPE TEXT;
